model:
  hidden_dim: "128_64"  # Hidden layer architecture in string format, e.g., "128_64" for two layers
  latent_dim: 32        # Required if "direct" mode is used
  non_linear: true
  beta: 1.0             # Required if "direct" mode is used
  learning_rate: 0.001  # Required if "direct" mode is used

training:
  epochs: 200
  batch_size: 64        # Required if "direct" mode is used
  early_stopping_patience: 20
  validation_split: 0.15

optuna: # Optional
  n_trials: 100
  cores_per_trial: 1
  study_name: "cvae_optimisation"
  search_space:
    hidden_dim:
      type: "categorical"
      choices: ["32", "64_32", "128_64"]
    latent_dim:
      type: "categorical"
      choices: [16, 32]
    learning_rate:
      type: "loguniform"
      min: 1e-5
      max: 1e-3
    batch_size:
      type: "categorical"
      choices: [32, 64]
    beta:
      type: "categorical"
      choices: [0.75, 1.0]

paths:
  data_dir: "/path/to/data/"
  output_dir: "/path/to/output/"
